# NumPy Basic Practice Questions

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>


Q.1) Given an nxn array, print only the elements that are greater than three as a 1D array.

Input: nxn array

Output: 1D array containing elements that are greater than 3

Sample Input 1: [[9,8,7],[6,5,4],[3,2,1]]

Sample Output 1: [9 8 7 6 5 4]

Sample Input 2: [[-1, 2, 0],[1,3,5],[3,2,1]]

Sample Output 2: [5]

In [1]:
import numpy as np
import ast
inp_list=ast.literal_eval(input())
arr=np.array(inp_list)
print(arr[arr>3])

[[9,8,7],[6,5,4],[3,2,1]]
[9 8 7 6 5 4]


Q.2) Calculate the 60th percentile of the given NumPy array.

Input: 1D array

Output: Value of 60th percentile rounded off to two decimal places

Sample Input 1: [11, 22, 33, 44 ,55 ,66, 77]

Sample Output 1: 50.6

Sample Input 2: [-1, 2, 0, 1, 3, 5, 3, 2, 1]

Sample Output 2: 2.0

In [2]:
import numpy as np
import ast
arr = np.array(ast.literal_eval(input()))
res = round(np.percentile(arr,60),2)
print(res)

[11, 22, 33, 44 ,55 ,66, 77]
50.6


Q.3) Given a positive integer 'n', write a program that computes the mean, the standard deviation and the variance of the numbers starting from 0 to n-1, rounded off to two decimal places.

Sample Input 1: 16

Sample Output 1: 

7.5

4.61

21.25

Explanation: 7.5, 4.61, and 21.5 are the mean, standard deviation and variance of the list of numbers from 0 to 15(included).


In [3]:
n=int(input())
array = np.arange(n)
mean = array.mean()
std = array.std()
variance = array.var()
print(f'Mean: {round(mean,2)}')
print(f'Standard deviation: {round(std,2)}')
print(f'Variance: {round(variance,2)}')

16
Mean: 7.5
Standard deviation: 4.61
Variance: 21.25


Q.4) Given a single positive integer 'n' greater than 2, create a NumPy array of size (n x n) will all zeros and ones such that the ones make a shape like 'Z'.
Examples:
Input 1:
3
Output 1:

[[1 1 1]

 [0 1 0]
 
 [1 1 1]]
 
Input 2:
5
Output 1:

[[1 1 1 1 1]

 [0 0 0 1 0]
 
 [0 0 1 0 0]
 
 [0 1 0 0 0]
 
 [1 1 1 1 1]]

Explanation: Notice that the 1s in the array make a shape like 'Z'.

In [4]:
n = int(input())
arr = np.zeros((n,n), dtype=int)
arr[0,:] = 1
arr[-1,:] = 1
for i in range(1,n-1):
    arr[i,-(i+1)] = 1
print(arr)


5
[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]


Q.5) Given a 2D NumPy array, sort it by the 1st column. Print the final sorted array as a NumPy array only.

Note: If two values in the 1st column are equal then the column in which the 2nd column value is lesser should come first. If the value in the second column is also the same then go to the third value and so on.

Example:
Input 1:

[[9 3 2]

 [4 0 1]
 
 [5 8 6]]
 
Output 2:

[[4 0 1]

 [5 8 6]
 
 [9 3 2]]
 
Input 2:

[[9 3 2]

 [4 0 1]
 
 [9 8 6]]
 
Output 2:

[[4 0 1]

 [9 3 2]
 
 [9 8 6]]

Explanation:
Example 1: Notice that the values in the first column are sorted. Also notice that the whole row should be moved and not just the individual values in the first column. For example, the row with the smallest value, i.e. 4 was moved as a whole. 

In [5]:
# arr = np.array([[9,3,2],[4,0,1],[5,8,6]])
input_list = ast.literal_eval(input())

arr = np.array(input_list)
sorted_indices = np.lexsort(arr[:, ::-1].T)

sorted_arr = arr[sorted_indices]

print(sorted_arr)


[[9,3,2],[4,0,1],[5,8,6]]
[[4 0 1]
 [5 8 6]
 [9 3 2]]
